-- ========================================
-- BugClose 测试数据脚本
-- 请在 H2 控制台中逐段执行
-- ========================================

-- ========================================
-- 1. 项目（PROJECTS）- 10 条
-- ========================================
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('支付中心', 'PAY', '统一支付平台，对接微信/支付宝/银联等渠道', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('客户关系管理', 'CRM', '客户信息管理、跟进记录、商机转化', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('电商平台', 'MALL', 'B2C 在线商城，含商品、订单、营销模块', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('办公自动化', 'OA', '内部审批、考勤、公告、通讯录', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('数据中台', 'DATA', '数据采集、清洗、报表与可视化', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('物流管理', 'WMS', '仓储管理、出入库、库存盘点', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('人力资源', 'HRM', '招聘、入离职、薪酬、绩效管理', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('在线教育', 'EDU', '课程管理、直播授课、作业考试', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('社交媒体', 'SNS', '动态发布、关注、评论、私信', CURRENT_TIMESTAMP);
INSERT INTO PROJECTS (NAME, CODE, DESCRIPTION, CREATED_AT) VALUES ('预约挂号', 'HOSP', '医院在线挂号、排班、就诊提醒', CURRENT_TIMESTAMP);

-- ========================================
-- 2. Bug（BUGS）- 10 条（分布在不同项目）
-- ========================================
INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (1, 1, '微信支付回调通知未处理导致订单状态不一致', '用户支付成功后，微信回调接口返回200但业务未更新订单状态，导致用户看到未支付。', 'CRITICAL', 'URGENT', 'IN_PROGRESS', '张三', '生产环境', '支付模块', '李四', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (2, 1, '客户列表分页查询超时', '当客户数据超过10万条时，列表页加载超过10秒，疑似缺少索引。', 'HIGH', 'HIGH', 'NEW', '王五', '测试环境', '客户管理', '赵六', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (3, 1, '商品详情页图片加载失败显示空白', 'CDN 图片链接失效后，详情页图片区域显示空白，缺少兜底图。', 'MEDIUM', 'MEDIUM', 'NEW', '张三', '测试环境', '商品模块', '李四', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (3, 2, '购物车数量修改后金额未实时更新', '在购物车页面修改商品数量后，底部合计金额未联动刷新，需手动刷新页面。', 'HIGH', 'URGENT', 'IN_PROGRESS', '王五', '测试环境', '购物车', '赵六', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (4, 1, '审批流程跳转后页面白屏', '提交请假审批后，跳转到审批详情页时出现白屏，控制台报 JS 错误。', 'HIGH', 'HIGH', 'RESOLVED', '张三', '测试环境', '审批模块', '李四', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (5, 1, '数据报表导出 CSV 文件中文乱码', '导出的 CSV 文件在 Excel 中打开时中文显示为乱码，需添加 BOM 头。', 'LOW', 'MEDIUM', 'NEW', '王五', '测试环境', '报表导出', '赵六', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (6, 1, '入库单重复提交导致库存多加', '网络延迟时用户连续点击提交按钮，入库单被创建两次，库存数量多加。', 'CRITICAL', 'URGENT', 'NEW', '张三', '生产环境', '入库管理', '李四', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (7, 1, '员工离职后账号仍可登录系统', '办理离职手续后，员工账号未被禁用，仍可正常登录 OA 系统。', 'CRITICAL', 'URGENT', 'IN_PROGRESS', '王五', '生产环境', '账号管理', '赵六', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (8, 1, '视频播放进度不保存', '在线课程视频播放中途退出后，再次进入从头开始播放，未记录上次进度。', 'MEDIUM', 'HIGH', 'NEW', '张三', '测试环境', '视频播放', '李四', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO BUGS (PROJECT_ID, SEQ, TITLE, DESCRIPTION, SEVERITY, PRIORITY, STATUS, ASSIGNEE, ENVIRONMENT, MODULE_NAME, REPORTER, IMAGES, CREATED_AT, UPDATED_AT)
VALUES (10, 1, '预约成功后未收到短信提醒', '用户预约挂号成功后未收到确认短信，疑似短信服务商接口超时未重试。', 'HIGH', 'HIGH', 'CLOSED', '王五', '生产环境', '短信通知', '赵六', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ========================================
-- 3. 测试用例（TEST_CASES）- 10 条
-- ========================================
INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 1, '微信支付正常下单并回调成功', '支付模块', 'P0', '已配置微信支付商户号及密钥', '1. 创建订单并选择微信支付\n2. 完成支付\n3. 检查订单状态', '订单状态更新为已支付，支付回调日志正常', 'PASS', '符合预期', '张三', CURRENT_TIMESTAMP, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (2, 1, '支付超时自动关闭订单', '支付模块', 'P1', '订单超时时间设置为30分钟', '1. 创建订单选择微信支付\n2. 不完成支付\n3. 等待30分钟', '订单自动关闭，库存回滚', 'PASS', '符合预期', '张三', CURRENT_TIMESTAMP, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 2, '新增客户信息并验证列表展示', '客户管理', 'P0', '已登录系统且有客户管理权限', '1. 点击新增客户\n2. 填写姓名、电话、公司\n3. 保存\n4. 在列表中搜索该客户', '客户新增成功，列表中可搜索到', 'PASS', '符合预期', '王五', CURRENT_TIMESTAMP, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (2, 3, '商品加入购物车并修改数量', '购物车', 'P0', '已登录且商品库存充足', '1. 商品详情页点击加入购物车\n2. 进入购物车\n3. 修改数量为5', '购物车数量显示为5，金额实时计算正确', 'FAIL', '金额未实时更新，需手动刷新', '王五', CURRENT_TIMESTAMP, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (3, 3, '商品搜索支持关键字模糊匹配', '商品模块', 'P2', '系统中已有商品数据', '1. 在搜索框输入关键字\n2. 查看搜索结果', '返回包含关键字的商品列表，支持名称和描述匹配', 'NOT_RUN', NULL, NULL, NULL, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 4, '提交请假审批流程', '审批模块', 'P0', '已配置请假审批流程模板', '1. 进入请假申请页面\n2. 填写请假类型和日期\n3. 提交审批\n4. 审批人审核通过', '审批流转正常，申请人收到通知', 'PASS', '符合预期', '张三', CURRENT_TIMESTAMP, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 5, '数据报表导出CSV文件', '报表导出', 'P1', '已有数据可供导出', '1. 进入报表页面\n2. 选择日期范围\n3. 点击导出CSV', 'CSV文件下载成功，数据与页面一致', 'FAIL', '中文乱码，缺少BOM头', '王五', CURRENT_TIMESTAMP, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 6, '入库单提交后库存增加', '入库管理', 'P0', '已创建待入库的SKU', '1. 创建入库单\n2. 填写入库数量\n3. 提交入库单', '库存数量正确增加，入库记录可查', 'BLOCKED', '依赖入库单接口修复', '张三', CURRENT_TIMESTAMP, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 8, '视频播放中途退出后再次进入', '视频播放', 'P1', '已上传课程视频资源', '1. 播放课程视频至50%\n2. 退出页面\n3. 重新进入播放', '视频从上次50%位置继续播放', 'NOT_RUN', NULL, NULL, NULL, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TEST_CASES (SEQ, PROJECT_ID, TITLE, MODULE_NAME, PRIORITY, PRECONDITION, STEPS, EXPECTED_RESULT, STATUS, ACTUAL_RESULT, EXECUTOR, EXECUTED_AT, DESIGNER, CREATED_AT, UPDATED_AT)
VALUES (1, 10, '预约挂号成功后收到短信通知', '短信通知', 'P0', '已配置短信服务商接口', '1. 选择科室和医生\n2. 选择时间段预约\n3. 确认预约', '预约成功，手机收到确认短信', 'PASS', '符合预期', '王五', CURRENT_TIMESTAMP, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ========================================
-- 4. 文档（DOCUMENTS）- 10 条
-- ========================================
INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (1, '支付中心需求规格说明书', 'REQUIREMENT', '支付中心V2.0完整需求文档，含微信支付、支付宝、银联对接方案', 1, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (1, '支付系统架构设计文档', 'DESIGN', '系统架构设计，含微服务拆分、数据库分库分表方案', 1, '张三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (2, 'CRM系统测试计划', 'TEST', 'CRM V1.0 系统测试计划，含测试范围、策略、用例设计', 1, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (3, '电商平台用户操作手册', 'MANUAL', '面向C端用户的操作指南，含注册、浏览、下单、支付全流程', 1, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (3, '商品模块接口文档', 'DESIGN', '商品CRUD、搜索、分类等RESTful API接口说明', 1, '张三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (4, 'OA系统Sprint评审会议纪要', 'MEETING', '2026-07-25 Sprint Review，讨论审批流程优化方案', 1, '王五', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (5, '数据中台技术方案', 'DESIGN', '数据采集、ETL流程、数据仓库建模方案', 1, '赵六', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (6, 'WMS系统需求文档', 'REQUIREMENT', '仓储管理系统需求，含入库、出库、盘点、库存预警', 1, '李四', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (8, '在线教育平台测试报告', 'TEST', 'V1.0 系统测试报告，含缺陷统计、通过率分析', 1, '张三', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO DOCUMENTS (PROJECT_ID, TITLE, CATEGORY, DESCRIPTION, LATEST_VERSION_NO, UPLOADER, CREATED_AT, UPDATED_AT)
VALUES (10, '预约挂号系统部署手册', 'MANUAL', '生产环境部署指南，含依赖服务、配置项、健康检查', 1, '王五', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ========================================
-- 5. 文档版本（DOCUMENT_VERSIONS）- 10 条（每个文档各一个初始版本）
-- ========================================
INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (1, 1, 'a1b2c3d4-req-spec.pdf', '支付中心需求规格说明书V1.0.pdf', 2048000, 'pdf', '初始版本', '李四', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (2, 1, 'e5f6g7h8-arch-design.docx', '支付系统架构设计文档.docx', 1536000, 'docx', '初始版本', '张三', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (3, 1, 'i9j0k1l2-test-plan.xlsx', 'CRM系统测试计划.xlsx', 512000, 'xlsx', '初始版本', '赵六', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (4, 1, 'm3n4o5p6-user-manual.pdf', '电商平台用户操作手册.pdf', 3072000, 'pdf', '初始版本', '李四', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (5, 1, 'q7r8s9t0-api-doc.md', '商品模块接口文档.md', 128000, 'md', '初始版本', '张三', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (6, 1, 'u1v2w3x4-meeting-notes.docx', 'OA Sprint评审会议纪要.docx', 256000, 'docx', '初始版本', '王五', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (7, 1, 'y5z6a7b8-tech-plan.pdf', '数据中台技术方案.pdf', 4096000, 'pdf', '初始版本', '赵六', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (8, 1, 'c9d0e1f2-req-wms.docx', 'WMS系统需求文档.docx', 1024000, 'docx', '初始版本', '李四', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (9, 1, 'g3h4i5j6-test-report.pdf', '在线教育平台测试报告.pdf', 768000, 'pdf', '初始版本', '张三', CURRENT_TIMESTAMP);

INSERT INTO DOCUMENT_VERSIONS (DOCUMENT_ID, VERSION_NO, STORED_NAME, ORIGINAL_FILENAME, FILE_SIZE, EXT, REMARK, UPLOADER, CREATED_AT)
VALUES (10, 1, 'k7l8m9n0-deploy-guide.md', '预约挂号系统部署手册.md', 192000, 'md', '初始版本', '王五', CURRENT_TIMESTAMP);

-- ========================================
-- 验证数据
-- ========================================
SELECT 'PROJECTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PROJECTS
UNION ALL SELECT 'BUGS', COUNT(*) FROM BUGS
UNION ALL SELECT 'TEST_CASES', COUNT(*) FROM TEST_CASES
UNION ALL SELECT 'DOCUMENTS', COUNT(*) FROM DOCUMENTS
UNION ALL SELECT 'DOCUMENT_VERSIONS', COUNT(*) FROM DOCUMENT_VERSIONS;
